version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tg_crypto_monitor:latest
    ports:
      - "3000:8000" # Host:Container
    volumes:
      - ./session:/session
    env_file:
      - .env.docker