version: '3.8'

services:
  app:
    # build: # Use this block to build the image locally
    #   context: .
    #   dockerfile: Dockerfile
      
    image: connorswislow/tg-crypto-monitor:latest
    ports:
      - "3000:8000" # Host:Container
    volumes:
      - ./session:/session
    env_file:
      - .env.docker